# Generated by Django 4.2.4 on 2023-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totallifetimefocus',
            name='overall_focus_time_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
