# Generated by Django 4.2.4 on 2023-09-28 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphics', '0002_alter_totallifetimefocus_overall_focus_time_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFocusTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('day_of_week', models.CharField(max_length=9)),
                ('total_focus_time_hours', models.FloatField()),
                ('week_number', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WeeklyFocusTime',
            },
        ),
    ]
