# Generated by Django 4.2.4 on 2023-09-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphics', '0003_weeklyfocustime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFocusTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_time', models.FloatField(default=0.0)),
                ('day_of_week', models.CharField(max_length=9)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DailyFocusTime',
            },
        ),
    ]
