# Generated by Django 4.2.4 on 2023-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_dailyfocustime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfocustime',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
