# Generated by Django 4.2.4 on 2023-09-29 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphics', '0005_alter_dailyfocustime_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('day_of_the_week', models.CharField(max_length=9)),
                ('week_number', models.IntegerField()),
                ('focus_time', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProgressReport',
            },
        ),
    ]
