# Generated by Django 4.2.4 on 2023-10-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0008_alter_userprogressreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogressreport',
            name='date',
            field=models.DateField(),
        ),
    ]
