# Generated by Django 4.2.4 on 2023-09-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='notes',
        ),
    ]
