# Generated by Django 4.2.4 on 2023-09-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='user_id',
        ),
    ]
