# Generated by Django 4.2.4 on 2023-09-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='user',
        ),
    ]
